In [1]:
import pandas as pd
import numpy as np

In [2]:
books = pd.read_csv(r'.\dataset\Books.csv', low_memory=False)
rating = pd.read_csv(r'.\dataset\Ratings.csv')
user = pd.read_csv(r'.\dataset\Users.csv')

print(books.shape)
print(rating.shape)
print(user.shape)

(271360, 8)
(1149780, 3)
(278858, 3)

In [3]:
# Count the total number of missing or NaN values in the books DataFrame
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [4]:
# Count the total number of missing or NaN values in the user DataFrame
user.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [5]:
# Count the total number of missing or NaN values in the rating DataFrame
rating.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [6]:
#finds duplicates
books.duplicated().sum()

0

In [7]:
user.duplicated().sum()

0

In [8]:
rating.duplicated().sum()

0

## Popularity based system

In [9]:
rating.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [10]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [11]:
rating_with_name = rating.merge(books, on="ISBN") 
dup_num = rating_with_name['Book-Title'].duplicated()
print(dup_num.head())

0    False
1     True
2     True
3     True
4     True
Name: Book-Title, dtype: bool

In [12]:
#grouping of data based on Book-Title
num_rating_df = rating_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'Num-Rating'}, inplace=True)
num_rating_df

                                               Book-Title  Num-Rating
0        A Light in the Storm: The Civil War Diary of ...           4
1                                   Always Have Popsicles           1
2                    Apple Magic (The Collector's series)           1
3        Ask Lily (Young Women of Faith: Lily Series, ...           1
4        Beyond IBM: Leadership Marketing and Finance ...           1
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.           2
241067                     Ã?Â?rger mit Produkt X. Roman.           4
241068                                Ã?Â?sterlich leben.           1
241069                              Ã?Â?stlich der Berge.           3
241070                                  Ã?Â?thique en toc           2

[241071 rows x 2 columns]

In [13]:
# Getting the index of null values
null_indices = rating_with_name[rating_with_name['Book-Rating'].isnull()].index
print(null_indices)

Index([], dtype='int64')

In [14]:
#grouping of data based on Book-Title
# print(rating_with_name['Book-Rating'].dtype)
avg_num_rating_df = rating_with_name.groupby('Book-Title')['Book-Rating'].mean().reset_index()
avg_num_rating_df.rename(columns={'Book-Rating':'Avg-Num-Rating'}, inplace=True)
print(avg_num_rating_df)

                                               Book-Title  Avg-Num-Rating
0        A Light in the Storm: The Civil War Diary of ...        2.250000
1                                   Always Have Popsicles        0.000000
2                    Apple Magic (The Collector's series)        0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...        8.000000
4        Beyond IBM: Leadership Marketing and Finance ...        0.000000
...                                                   ...             ...
241066                                      Ã?Â?lpiraten.        0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.        5.250000
241068                                Ã?Â?sterlich leben.        7.000000
241069                              Ã?Â?stlich der Berge.        2.666667
241070                                  Ã?Â?thique en toc        4.000000

[241071 rows x 2 columns]

In [15]:
popular_df = num_rating_df.merge(avg_num_rating_df, on='Book-Title')
popular_df

,Book-Title,Num-Rating,Avg-Num-Rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [16]:
# Top 50 books based on user ratings
popular_df = popular_df[popular_df['Num-Rating'] > 250].sort_values('Avg-Num-Rating', ascending=False).head(50)

In [17]:
# popular_df.keys() # Extract indexes from the dataframe
popular_df = popular_df.merge(books, on='Book-Title').drop_duplicates('Book-Title')
popular_df = popular_df[['Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher', 'Image-URL-S', 'Avg-Num-Rating', 'Num-Rating']]
popular_df

,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Avg-Num-Rating,Num-Rating
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439136350.0...,5.852804,428
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439139597.0...,5.824289,387
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,1998,Scholastic,http://images.amazon.com/images/P/0590353403.0...,5.737410,278
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,2003,Scholastic,http://images.amazon.com/images/P/043935806X.0...,5.501441,347
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439064872.0...,5.183453,556
16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339681.0...,5.007117,281
17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339703.0...,4.948370,368
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,1999,Arthur A. Levine Books,http://images.amazon.com/images/P/059035342X.0...,4.895652,575
28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339711.0...,4.880769,260
39,To Kill a Mockingbird,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,4.700000,510
47,The Da Vinci Code,Dan Brown,2003,Doubleday,http://images.amazon.com/images/P/0385504209.0...,4.642539,898
53,The Five People You Meet in Heaven,Mitch Albom,2003,Hyperion,http://images.amazon.com/images/P/0786868716.0...,4.551163,430
55,The Catcher in the Rye,J.D. Salinger,1991,"Little, Brown",http://images.amazon.com/images/P/0316769487.0...,4.545657,449
62,The Lovely Bones: A Novel,Alice Sebold,2002,"Little, Brown",http://images.amazon.com/images/P/0316666343.0...,4.468726,1295
63,1984,George Orwell,1990,Signet Book,http://images.amazon.com/images/P/0451524934.0...,4.454225,284
72,Prodigal Summer: A Novel,Barbara Kingsolver,2001,Perennial,http://images.amazon.com/images/P/0060959037.0...,4.450593,253
73,Neverwhere,Neil Gaiman,1998,Avon,http://images.amazon.com/images/P/0380789019.0...,4.449057,265
78,The Secret Life of Bees,Sue Monk Kidd,2003,Penguin Books,http://images.amazon.com/images/P/0142001740.0...,4.447028,774
84,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,2002,Regan Books,http://images.amazon.com/images/P/0060392452.0...,4.356890,283
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,1997,Doubleday,http://images.amazon.com/images/P/0385484518.0...,4.354970,493
88,The Red Tent (Bestselling Backlist),Anita Diamant,1998,Picador USA,http://images.amazon.com/images/P/0312195516.0...,4.334716,723
89,The Hitchhiker's Guide to the Galaxy,Douglas Adams,1982,Pocket,http://images.amazon.com/images/P/0671461494.0...,4.328358,268
98,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,2002,Owl Books,http://images.amazon.com/images/P/0805063897.0...,4.289552,335
100,Into the Wild,Jon Krakauer,1997,Anchor,http://images.amazon.com/images/P/0385486804.0...,4.273810,252
103,Fahrenheit 451,Ray Bradbury,1994,Distribooks Inc,http://images.amazon.com/images/P/3257208626.0...,4.264059,409
116,Girl with a Pearl Earring,Tracy Chevalier,2001,Plume Books,http://images.amazon.com/images/P/0452282152.0...,4.218631,526
117,Outlander,DIANA GABALDON,1996,Dell,http://images.amazon.com/images/P/0440222915.0...,4.173145,283
123,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,1998,Warner Books,http://images.amazon.com/images/P/0446672211.0...,4.105983,585
124,Seabiscuit: An American Legend,LAURA HILLENBRAND,2002,Ballantine Books,http://images.amazon.com/images/P/0449005615.0...,4.098182,275
126,Life of Pi,Yann Martel,2002,Harcourt,http://images.amazon.com/images/P/0151008116.0...,4.088855,664
130,The Bean Trees,Barbara Kingsolver,1989,Perennial,http://images.amazon.com/images/P/0060915544.0...,4.087404,389
133,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,1995,Health Communications,http://images.amazon.com/images/P/1558743669.0...,4.086792,265
135,ANGELA'S ASHES,Frank McCourt,1996,Scribner,http://images.amazon.com/images/P/0684874350.0...,4.075269,279
137,Good in Bed,Jennifer Weiner,2002,Washington Square Press,http://images.amazon.com/images/P/0743418174.0...,4.055102,490
139,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,2002,Perennial,http://images.amazon.com/images/P/0060938455.0...,4.037383,321
140,American Gods,Neil Gaiman,2002,HarperTorch,http://images.amazon.com/images/P/0380789035.0...,4.006623,302
141,Skipping Christmas,JOHN GRISHAM,2001,Doubleday,http://images.amazon.com/images/P/0385505833.0...,4.006211,322
147,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,1996,Tyndale House Publishers,http://images.amazon.com/images/P/0842329129.0...,4.003145,318
149,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,2002,Knopf Books for Young Readers,http://images.amazon.com/images/P/037582345X.0...,4.000000,336
157,The Color Purple,Alice Walker,1985,Pocket Books,http://images.amazon.com/images/P/0671617028.0...,3.964968,314
163,Silence of the Lambs,Thomas Harris,1991,St. Martin's Press,http://images.amazon.com/images/P/0312924585.0...,3.960938,256
166,About a Boy,Nick Hornby,1999,Riverhead Books,http://images.amazon.com/images/P/1573227331.0...,3.900763,262
173,Seven Up (A Stephanie Plum Novel),Janet Evanovich,2001,St. Martin's Press,http://images.amazon.com/images/P/0312265840.0...,3.888489,278
175,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,1993,HarperSanFrancisco,http://images.amazon.com/images/P/0062502174.0...,3.875940,266
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,2003,St. Martin's Paperbacks,http://images.amazon.com/images/P/0312983867.0...,3.825279,269
182,Suzanne's Diary for Nicholas,James Patterson,2001,"Little, Brown",http://images.amazon.com/images/P/0316969443.0...,3.820569,457
186,Lord of the Flies,William Gerald Golding,1959,Perigee Trade,http://images.amazon.com/images/P/0399501487.0...,3.818533,259
192,A Prayer for Owen Meany,John Irving,1990,Ballantine Books,http://images.amazon.com/images/P/0345361792.0...,3.796610,413
194,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,1986,Ballantine Books,http://images.amazon.com/images/P/0345313860.0...,3.777409,301
195,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,2000,Back Bay Books,http://images.amazon.com/images/P/0316284955.0...,3.772472,356

## Collaborative filtering

In [18]:
user_rating = rating_with_name.groupby('User-ID').count()['Book-Rating'] > 200
user_ratings = user_rating[user_rating].index
filtered_rating = rating_with_name[rating_with_name['User-ID'].isin(user_ratings)]  #only consider the users that satisfies the above criteria i.e. they have given minimum of more than 200 ratings.

In [19]:
famous_books = filtered_rating.groupby('Book-Title').count()['Book-Rating'] >= 50
famous_books = famous_books[famous_books].index
famous_books  #Only considered the books that have got total ratings count more than 50

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=706)

In [29]:
# Considered only that books which have got atleast 50 ratings and only rated by the user who have given ratings to more than 200 books
final_rated_books = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

(58586, 10)

In [21]:
# Pivot table
pt = final_rated_books.pivot_table(index='Book-Title', columns='User-ID', values='Book-Rating')
pt.fillna(0, inplace=True)
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [22]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_scores = cosine_similarity(pt)
similarity_scores.shape
similarity_scores

array([[1.        , 0.10255025, 0.01220856, ..., 0.12110367, 0.07347567,
        0.04316046],
       [0.10255025, 1.        , 0.2364573 , ..., 0.07446129, 0.16773875,
        0.14263397],
       [0.01220856, 0.2364573 , 1.        , ..., 0.04558758, 0.04938579,
        0.10796119],
       ...,
       [0.12110367, 0.07446129, 0.04558758, ..., 1.        , 0.07085128,
        0.0196177 ],
       [0.07347567, 0.16773875, 0.04938579, ..., 0.07085128, 1.        ,
        0.10602962],
       [0.04316046, 0.14263397, 0.10796119, ..., 0.0196177 , 0.10602962,
        1.        ]])

In [23]:
def recommend(book_name):
    #fetching index
    # np.where(pt.index==f"{book_name}") returns 2D array [0][0] gives the 0th pos index number
    index = np.where(pt.index==f"{book_name}")[0][0]
    #finding vector distances with other books
    # distances = list(enumerate(similarity_scores[index]))
    # finding similar items
    similar_items_index = sorted(list(enumerate(similarity_scores[index])), key = lambda x : x[1],reverse=True)[1:11]

    # book_index = [index, distance]
    data = []
    for book_index in similar_items_index:
        # print(book_index)
        item = []
        temp_df = books[books['Book-Title'] == pt.index[book_index[0]]] #Getting similar book name using index
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        data.append(item)
    
    return data

In [24]:
recommend('The Da Vinci Code') #sample

[['Angels &amp; Demons',
  'Dan Brown',
  'http://images.amazon.com/images/P/0671027360.01.MZZZZZZZ.jpg'],
 ['Touching Evil',
  'Kay Hooper',
  'http://images.amazon.com/images/P/0553583441.01.MZZZZZZZ.jpg'],
 ['Saving Faith',
  'David Baldacci',
  'http://images.amazon.com/images/P/0446608890.01.MZZZZZZZ.jpg'],
 ["The Sweet Potato Queens' Book of Love",
  'JILL CONNER BROWNE',
  'http://images.amazon.com/images/P/0609804138.01.MZZZZZZZ.jpg'],
 ['Middlesex: A Novel',
  'Jeffrey Eugenides',
  'http://images.amazon.com/images/P/0312422156.01.MZZZZZZZ.jpg'],
 ['The Lovely Bones: A Novel',
  'Alice Sebold',
  'http://images.amazon.com/images/P/0316666343.01.MZZZZZZZ.jpg'],
 ['Timeline',
  'MICHAEL CRICHTON',
  'http://images.amazon.com/images/P/0345417623.01.MZZZZZZZ.jpg'],
 ['The Blue Nowhere : A Novel',
  'Jeffery Deaver',
  'http://images.amazon.com/images/P/0671042262.01.MZZZZZZZ.jpg'],
 ['Sea Glass: A Novel',
  'Anita Shreve',
  'http://images.amazon.com/images/P/0316089699.01.MZZZZZZZ.jpg'],
 ["Bridget Jones's Diary",
  'Helen Fielding',
  'http://images.amazon.com/images/P/0330332775.01.MZZZZZZZ.jpg']]

In [26]:
# Serializing models using pickle
import pickle
pickle.dump(popular_df, open('popular.pkl', 'wb'))
pickle.dump(pt, open('pt.pkl', 'wb'))
pickle.dump(books, open('books.pkl', 'wb'))
pickle.dump(similarity_scores, open('similarity_score.pkl', 'wb'))